Update create_branch.yml

diff --git a/.github/workflows/create_branch.yml b/.github/workflows/create_branch.yml
--- a/.github/workflows/create_branch.yml
+++ b/.github/workflows/create_branch.yml
@@ -1,29 +1,34 @@
-name: Create branch
+name: Create Branch
 
 on:
-    workflow_dispatch:
-        inputs:
-            branch_name:
-                description: "Enter branch name"
-                required: true
-                default: new-branch
+  workflow_dispatch:
+    inputs:
+      branch_name:
+        description: 'Branch name to create'
+        required: true
+        default: 'new-branch'
 
-            
 jobs:
-    create_branch:
-        runs-on: ubuntu-latest
+  create_branch:
+    runs-on: ubuntu-latest
 
-        steps:      
-        - name: Checkout repository
-          uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-        - name: Create a new branch
-          run: |
-            git config user.name "github-actions[bot]"
-            git config user.email "github-actions[bot]@users.noreply.github.com"
-            git checkout -b ${{github.action.inputs.branch_name}}
-            git push origin ${{github.action.inputs.branch_name}}
+      - name: Validate branch name input
+        run: |
+          if [ -z "${{ github.event.inputs.branch_name }}" ]; then
+            echo "Branch name input is required!"
+            exit 1
+          fi
 
-        - name: Confirm branch creation
-          run: echo "Branch ${{github.action.inputs.branch_name}} created sussussfully"
-         
+      - name: Create new branch
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git checkout -b ${{ github.event.inputs.branch_name }}
+          git push origin ${{ github.event.inputs.branch_name }}
+
+      - name: Confirm branch creation
+        run: echo "Branch ${{ github.event.inputs.branch_name }} created successfully!"
